# Generated by Django 4.1.13 on 2026-05-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.CharField(max_length=255)),
                ('description_full', models.TextField()),
                ('image', models.ImageField(upload_to='experiences/')),
                ('tech_stack', models.CharField(help_text='Comma separated list, e.g. React, Tailwind, Django', max_length=200)),
                ('features', models.TextField(help_text='Pipe separated list, e.g. Feature 1 | Feature 2')),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('source_code_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
