# Generated by Django 4.1.13 on 2026-05-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0002_experience_delete_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='features',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='image',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='live_demo_url',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='source_code_url',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='tech_stack',
        ),
    ]
