# Generated by Django 4.1.13 on 2026-05-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0003_remove_experience_features_remove_experience_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experiences/'),
        ),
    ]
